# Generated by Django 4.2.7 on 2025-08-31 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('inquiry_type', models.CharField(choices=[('rental', 'Yacht Rental Interest'), ('purchase', 'Yacht Purchase Interest'), ('fractional', 'Fractional Ownership Interest'), ('charter', 'Private Charter Interest'), ('general', 'General Information Request')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Initial Contact Made'), ('qualified', 'Qualified Lead'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'In Negotiations'), ('closed_won', 'Closed - Won'), ('closed_lost', 'Closed - Lost'), ('nurturing', 'Long-term Nurturing')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('phone', 'Phone Call'), ('email', 'Direct Email'), ('referral', 'Customer Referral'), ('social_media', 'Social Media'), ('boat_show', 'Boat Show'), ('advertisement', 'Advertisement'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='website', max_length=20)),
                ('budget_range_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget in USD', max_digits=12, null=True)),
                ('budget_range_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget in USD', max_digits=12, null=True)),
                ('timeline', models.CharField(blank=True, help_text='Purchase/rental timeline', max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(help_text='Initial inquiry message')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal sales notes')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('lead_score', models.PositiveIntegerField(default=0, help_text='Lead score (0-100)')),
                ('is_qualified', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False, help_text='Consented to marketing communications')),
                ('consent_data_processing', models.BooleanField(default=True, help_text='Consented to data processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('boat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='boats.boat')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries_inquiry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost_per_lead', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('qualified_leads', models.PositiveIntegerField(default=0)),
                ('closed_deals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead Source',
                'verbose_name_plural': 'Lead Sources',
                'db_table': 'inquiries_lead_source',
            },
        ),
        migrations.CreateModel(
            name='InquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'In-Person Meeting'), ('video_call', 'Video Call'), ('proposal', 'Proposal Sent'), ('brochure', 'Brochure Sent'), ('boat_viewing', 'Boat Viewing'), ('sea_trial', 'Sea Trial'), ('negotiation', 'Contract Negotiation'), ('other', 'Other Activity')], max_length=20)),
                ('outcome', models.CharField(choices=[('successful', 'Successful Contact'), ('no_answer', 'No Answer'), ('voicemail', 'Left Voicemail'), ('email_sent', 'Email Sent'), ('meeting_scheduled', 'Meeting Scheduled'), ('interested', 'Showed Interest'), ('not_interested', 'Not Interested'), ('needs_time', 'Needs Time to Decide'), ('request_info', 'Requested More Information')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Activity duration in minutes', null=True)),
                ('contact_method', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('next_action_date', models.DateTimeField(blank=True, null=True)),
                ('next_action_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='inquiries.inquiry')),
            ],
            options={
                'verbose_name': 'Inquiry Follow-up',
                'verbose_name_plural': 'Inquiry Follow-ups',
                'db_table': 'inquiries_inquiry_follow_up',
                'ordering': ['-created_at'],
            },
        ),
    ]
