# Generated by Django 4.2.7 on 2025-08-26 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('D29', 'De Antonio D29'), ('D32', 'De Antonio D32'), ('D36', 'De Antonio D36'), ('D42', 'De Antonio D42'), ('D50', 'De Antonio D50'), ('D60', 'De Antonio D60')], max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(default='El Gouna, Egypt', max_length=255)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in meters', max_digits=5)),
                ('capacity', models.IntegerField(help_text='Maximum passengers')),
                ('cabins', models.IntegerField()),
                ('max_power', models.IntegerField(blank=True, help_text='Maximum HP', null=True)),
                ('year_built', models.IntegerField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seasonal_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('booked', 'Currently Booked'), ('sold_out', 'Fully Owned')], default='available', max_length=20)),
                ('images', models.JSONField(default=list, help_text='Array of image URLs')),
                ('amenities', models.JSONField(default=list, help_text='Yacht amenities and features')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_yachts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yachts',
                'ordering': ['model', 'name'],
            },
        ),
        migrations.CreateModel(
            name='YachtSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('fuel_capacity', models.IntegerField(blank=True, help_text='Liters', null=True)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='L/hour', max_digits=5, null=True)),
                ('max_speed', models.IntegerField(blank=True, help_text='Knots', null=True)),
                ('cruising_speed', models.IntegerField(blank=True, help_text='Knots', null=True)),
                ('beam', models.DecimalField(blank=True, decimal_places=2, help_text='Meters', max_digits=4, null=True)),
                ('draft', models.DecimalField(blank=True, decimal_places=2, help_text='Meters', max_digits=3, null=True)),
                ('water_capacity', models.IntegerField(blank=True, help_text='Liters', null=True)),
                ('navigation_equipment', models.JSONField(default=list)),
                ('safety_equipment', models.JSONField(default=list)),
                ('comfort_features', models.JSONField(default=list)),
                ('yacht', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='yachts.yacht')),
            ],
            options={
                'db_table': 'yacht_specifications',
            },
        ),
        migrations.CreateModel(
            name='YachtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yachts/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yacht_images', to='yachts.yacht')),
            ],
            options={
                'db_table': 'yacht_images',
                'ordering': ['order', 'is_primary'],
            },
        ),
        migrations.CreateModel(
            name='YachtAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, help_text='Reason if not available', max_length=100)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='yachts.yacht')),
            ],
            options={
                'db_table': 'yacht_availability',
                'ordering': ['date'],
                'unique_together': {('yacht', 'date')},
            },
        ),
    ]
