# Generated by Django 4.2.7 on 2025-08-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Yacht name', max_length=100)),
                ('model', models.CharField(help_text='Yacht model (e.g., D42, D50)', max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of passengers')),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in meters', max_digits=5)),
                ('beam', models.DecimalField(blank=True, decimal_places=2, help_text='Beam width in meters', max_digits=4, null=True)),
                ('location', models.CharField(help_text='Current location/marina', max_length=100)),
                ('allow_public_rental', models.BooleanField(default=True, help_text='Available for public rental')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rental rate', max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Yacht description')),
                ('image_url', models.URLField(blank=True, help_text='Main yacht image URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boat',
                'verbose_name_plural': 'Boats',
                'db_table': 'boats_boat',
                'ordering': ['model', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoatFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_value', models.CharField(blank=True, max_length=200)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='boats.boat')),
            ],
            options={
                'db_table': 'boats_boat_feature',
            },
        ),
    ]
