# Generated by Django 4.2.7 on 2025-08-31 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('fuel_low_balance', 'Fuel Wallet Low Balance'), ('fuel_purchase_confirmed', 'Fuel Purchase Confirmed'), ('ownership_share_available', 'Ownership Share Available'), ('inquiry_received', 'New Inquiry Received'), ('inquiry_update', 'Inquiry Status Update'), ('system_maintenance', 'System Maintenance Alert'), ('welcome_message', 'Welcome Message'), ('security_alert', 'Security Alert'), ('promotional', 'Promotional Message')], max_length=30, unique=True)),
                ('title_template', models.CharField(help_text='Title template with placeholders like {yacht_name}', max_length=200)),
                ('message_template', models.TextField(help_text='Message template with placeholders')),
                ('available_variables', models.JSONField(default=list, help_text="List of available template variables like ['yacht_name', 'booking_date']")),
                ('default_priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('default_action_text', models.CharField(blank=True, max_length=50)),
                ('send_push', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=False)),
                ('send_sms', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='Template description for admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notify_system_notification_template',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=False)),
                ('booking_notifications', models.BooleanField(default=True)),
                ('payment_notifications', models.BooleanField(default=True)),
                ('fuel_notifications', models.BooleanField(default=True)),
                ('ownership_notifications', models.BooleanField(default=True)),
                ('inquiry_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('promotional_notifications', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='immediate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notify_system_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('fuel_low_balance', 'Fuel Wallet Low Balance'), ('fuel_purchase_confirmed', 'Fuel Purchase Confirmed'), ('ownership_share_available', 'Ownership Share Available'), ('inquiry_received', 'New Inquiry Received'), ('inquiry_update', 'Inquiry Status Update'), ('system_maintenance', 'System Maintenance Alert'), ('welcome_message', 'Welcome Message'), ('security_alert', 'Security Alert'), ('promotional', 'Promotional Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('action_url', models.URLField(blank=True, help_text='Deep link for mobile app or web URL')),
                ('action_text', models.CharField(blank=True, help_text="Button text like 'View Booking'", max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_push', models.BooleanField(default=False, help_text='Sent as push notification')),
                ('sent_email', models.BooleanField(default=False, help_text='Sent as email')),
                ('sent_sms', models.BooleanField(default=False, help_text='Sent as SMS')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule notification for future delivery', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expiration time', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notify_system_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notify_syst_user_id_ecd956_idx'), models.Index(fields=['user', 'is_read'], name='notify_syst_user_id_91caf8_idx'), models.Index(fields=['notification_type'], name='notify_syst_notific_4cce1e_idx'), models.Index(fields=['scheduled_for'], name='notify_syst_schedul_6001b0_idx')],
            },
        ),
    ]
