# Generated by Django 4.2.7 on 2025-08-31 11:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current fuel credit balance', max_digits=10)),
                ('total_purchased', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fuel credits purchased', max_digits=12)),
                ('total_consumed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fuel credits consumed', max_digits=12)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Alert when balance drops below this amount', max_digits=8)),
                ('auto_topup_enabled', models.BooleanField(default=False)),
                ('auto_topup_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fuel Wallet',
                'verbose_name_plural': 'Fuel Wallets',
                'db_table': 'ownership_fuel_wallet',
            },
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('seasonal_multiplier', 'Seasonal Rate Multiplier'), ('advance_booking', 'Advance Booking Requirement'), ('minimum_stay', 'Minimum Stay Requirement'), ('blackout_period', 'Blackout Period'), ('owner_priority', 'Owner Priority Period')], max_length=30)),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('multiplier_value', models.DecimalField(blank=True, decimal_places=2, help_text='Rate multiplier (e.g., 1.5 for 50% increase)', max_digits=4, null=True)),
                ('days_requirement', models.PositiveIntegerField(blank=True, help_text='Days for advance booking or minimum stay', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rules', to='boats.boat')),
            ],
            options={
                'verbose_name': 'Booking Rule',
                'verbose_name_plural': 'Booking Rules',
                'db_table': 'ownership_booking_rule',
            },
        ),
        migrations.CreateModel(
            name='FractionalOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.CharField(choices=[('1/8', '1/8 Share (6 weeks/year)'), ('1/4', '1/4 Share (12 weeks/year)'), ('1/2', '1/2 Share (26 weeks/year)'), ('full', 'Full Ownership')], max_length=10)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_day_limit', models.PositiveIntegerField(default=48, help_text='Days per year allowed')),
                ('annual_hour_limit', models.PositiveIntegerField(default=50, help_text='Engine hours per year')),
                ('current_year_days_used', models.PositiveIntegerField(default=0)),
                ('current_year_hours_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='boats.boat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yacht_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fractional Ownership',
                'verbose_name_plural': 'Fractional Ownerships',
                'db_table': 'ownership_fractional_ownership',
                'unique_together': {('boat', 'owner')},
            },
        ),
    ]
